#:schema node_modules/wrangler/config-schema.json
# wrangler.toml
name = '6mlc3o'
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-03-28"
main = "worker.ts"
send_metrics = false

[site]
bucket = "./build/client"
